sudo: required
services:
 - docker

before_install:
 - docker build -t hereisvishal/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true hereisvishal/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "eu-north-1"
 app: "docker-react"
 env: "Docker-react-env"
 bucket_name: "elasticbeanstalk-eu-north-1-534900895013"
 bucket_path: "docker-react"
 on:
  branch: main
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: "$AWS_SECRET_ACCESS_KEY"

 
